PUT   https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
    "id": 1,
    "title": "Meu post atualizado",
    "body": "Agora estou aprendendo PUT!",
    "userId": 1
}

